export const BUTTON_TYPES = {
  BUTTON_DIGIT: 'BUTTON_DIGIT',
  BUTTON_CONTROL: 'BUTTON_CONTROL',
  BUTTON_UTILITE: 'BUTTON_UTILITE',
  BUTTON_WIDE: 'BUTTON_WIDE',
};

export const ACTIONS = {
  SUM: 'SUM',
  SUB: 'SUB',
  RES: 'RES',
};

export const MAX_FORMULA_LENGTH = 10;
